sudo: required
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev .

script: 'true'
on:
  branch: master